YALB-1442: WYSIWYG Creating and editing a table is visually and functionally broken
yalesites-org/atomic pull request #155
Opened 2023-07-21 17:41 UTC by dblanken-yale

## [YALB-1442: WYSIWYG Creating and editing a table is visually and functionally broken](https://yaleits.atlassian.net/browse/YALB-1442)

### Description of work
- Add ckeditor-overrides.css file
- Add styling to `.cke_dialog` elements that are more in line with our theme
  - No ugly black border lines all over the place
  - Attempt to style inputs and selects to match our style in other places
  - Style buttons to look like our theme

### Functional testing steps:
- [ ] Step 1
- [ ] Step 2
- [ ] Step 3
- [ ] ...

2023-07-21 19:02 UTC, dblanken-yale commented
@joetower I'm adding you since it's mostly CSS changes to manipulate how the table modal in CKEditor looks.

@codechefmarc I added you in case I placed the css file in an inappropriate spot.  Let me know if you can think of a better place for it.

@myvaughn and @kara-franco While I don't think we can modify much with the table, if there are any CSS-related things we need to do for accessibility, let me know.

2023-07-21 21:42 UTC, myvaughn requested changes
Just considering the color contrast, the "Table Properties" header, the --mediterranean-blue (#187e9b) with --wool (#fbfbf6) on top has a contrast ratio of 4.49:1, just missing the required 4.5:1. It would pass with white instead for the text (4.67:1).

2023-07-24 12:47 UTC, dblanken-yale reviewed
Ok, the push should convert wool to white.  :D

2023-07-24 18:23 UTC, myvaughn approved these changes
Tried to verify on https://pr-362-yalesites-platform.pantheonsite.io/ but it's not changed there. If the text is white now, I approve.

2023-07-25 19:57 UTC, codechefmarc approved these changes
This looked good to me - In this branch, the modal wasn't allowing me to edit values, but I think that was fixed in your other branch. The styling looks good to me, though! And the placement of the CSS works for me to split that out since we will (most likely) make more CSS changes for CKEditor in the future with CKEditor5, is my guess.

2023-07-25 20:01 UTC, merged