YALB 634 wire footer
yalesites-org/atomic pull request #29
Opened 2022-07-28 21:50 UTC by codeb-a

## [YALB-634: Wire Footer](https://yaleits.atlassian.net/browse/YALB-634)

### Description of work
- Adds social links block to footer region

### Functional testing steps:
- [ ] login 
- [ ] Navigate to footer

2022-07-29 11:13 UTC, ModulesUnraveled approved these changes
Looks good. :shipit:

2022-07-29 11:20 UTC, ModulesUnraveled requested changes

2022-07-29 11:20 UTC, ModulesUnraveled commented on templates/ys/ys-social-links.html.twig
> +{% include '@molecules/social-links/social-links.twig' %}
I just realized that we didn't consider what happens when no social media fields are filled out. I expect it'll still print empty markup to the page. We should check that, and add an `if` statement or something to only include this template if at least one of the fields is filled in.

2022-07-29 18:31 UTC, ModulesUnraveled approved these changes
That does it. Thanks!

2022-07-31 20:53 UTC, nJim commented
Merging this work into develop as I'm preparing for demo. Great job.

2022-07-31 20:53 UTC, merged